server:
  port: 8080
hello:
  name: 林玉坤
  address: 北京

lyk:
  swagger2:
    base_package: ncepu.lykkk.exercise.controller
    title: 测试swagger2文档标题
    description: 测试swagger2文档描述
    name: 林玉坤
    url: http://localhost:8080/doc.html
    email: 1076329840@qq.com
    version: 0.1
spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher