server:
  port: 8080

lyk:
  swagger2:
    enabled: true
    version: 1.0
    description: 新式描述
    title: 新式标题
    base-package:  ncepu.lykkk.exercise.controller
    contact:
      email: 1076329840@qq.com
      name: 林玉坤1111
      url: localhost:8080/doc.html

spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher