server:
  port: 9000

lyk:
  swagger2:
    base_package: ncepu.lykkk.exercise.controller
    title: validator接口文档
    description: validator接口文档描述
    name: 林玉坤
    url: http://localhost:8080/doc.html
    email: 1076329840@qq.com
    version: 0.1
spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher